// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQxat2l2ueCxxjqzdnOUGOj8pTE8pDDDY',
    appId: '1:1082747220622:web:034460b3f53c8a49830fdf',
    messagingSenderId: '1082747220622',
    projectId: 'finalproject-fcafa',
    authDomain: 'finalproject-fcafa.firebaseapp.com',
    storageBucket: 'finalproject-fcafa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS3QxZ5ujHG65ti0SMIkyo8jX36dkLFGs',
    appId: '1:1082747220622:android:fcb4a0ff50f0f751830fdf',
    messagingSenderId: '1082747220622',
    projectId: 'finalproject-fcafa',
    storageBucket: 'finalproject-fcafa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lFtBvUuSMQyaH4K1XQMQhQWD0CDDopo',
    appId: '1:1082747220622:ios:f175d2c2257d405f830fdf',
    messagingSenderId: '1082747220622',
    projectId: 'finalproject-fcafa',
    storageBucket: 'finalproject-fcafa.firebasestorage.app',
    iosBundleId: 'com.example.habify3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lFtBvUuSMQyaH4K1XQMQhQWD0CDDopo',
    appId: '1:1082747220622:ios:f175d2c2257d405f830fdf',
    messagingSenderId: '1082747220622',
    projectId: 'finalproject-fcafa',
    storageBucket: 'finalproject-fcafa.firebasestorage.app',
    iosBundleId: 'com.example.habify3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQxat2l2ueCxxjqzdnOUGOj8pTE8pDDDY',
    appId: '1:1082747220622:web:56fad01d9404d100830fdf',
    messagingSenderId: '1082747220622',
    projectId: 'finalproject-fcafa',
    authDomain: 'finalproject-fcafa.firebaseapp.com',
    storageBucket: 'finalproject-fcafa.firebasestorage.app',
  );

}